# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msgpb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import raft_cmdpb_pb2 as raft__cmdpb__pb2
import raft_serverpb_pb2 as raft__serverpb__pb2
import kvrpcpb_pb2 as kvrpcpb__pb2
import coprocessor_pb2 as coprocessor__pb2
import pdpb_pb2 as pdpb__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='msgpb.proto',
  package='msgpb',
  syntax='proto2',
  serialized_pb=_b('\n\x0bmsgpb.proto\x12\x05msgpb\x1a\x10raft_cmdpb.proto\x1a\x13raft_serverpb.proto\x1a\rkvrpcpb.proto\x1a\x11\x63oprocessor.proto\x1a\npdpb.proto\"\x8b\x03\n\x07Message\x12$\n\x08msg_type\x18\x01 \x01(\x0e\x32\x12.msgpb.MessageType\x12+\n\x07\x63md_req\x18\x02 \x01(\x0b\x32\x1a.raft_cmdpb.RaftCmdRequest\x12-\n\x08\x63md_resp\x18\x03 \x01(\x0b\x32\x1b.raft_cmdpb.RaftCmdResponse\x12(\n\x04raft\x18\x04 \x01(\x0b\x32\x1a.raft_serverpb.RaftMessage\x12 \n\x06kv_req\x18\x05 \x01(\x0b\x32\x10.kvrpcpb.Request\x12\"\n\x07kv_resp\x18\x06 \x01(\x0b\x32\x11.kvrpcpb.Response\x12%\n\x07\x63op_req\x18\x07 \x01(\x0b\x32\x14.coprocessor.Request\x12\'\n\x08\x63op_resp\x18\x08 \x01(\x0b\x32\x15.coprocessor.Response\x12\x1d\n\x06pd_req\x18\t \x01(\x0b\x32\r.pdpb.Request\x12\x1f\n\x07pd_resp\x18\n \x01(\x0b\x32\x0e.pdpb.Response*~\n\x0bMessageType\x12\x08\n\x04None\x10\x00\x12\x07\n\x03\x43md\x10\x01\x12\x0b\n\x07\x43mdResp\x10\x02\x12\x08\n\x04Raft\x10\x03\x12\t\n\x05KvReq\x10\x04\x12\n\n\x06KvResp\x10\x05\x12\n\n\x06\x43opReq\x10\x06\x12\x0b\n\x07\x43opResp\x10\x07\x12\t\n\x05PdReq\x10\x08\x12\n\n\x06PdResp\x10\t')
  ,
  dependencies=[raft__cmdpb__pb2.DESCRIPTOR,raft__serverpb__pb2.DESCRIPTOR,kvrpcpb__pb2.DESCRIPTOR,coprocessor__pb2.DESCRIPTOR,pdpb__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_MESSAGETYPE = _descriptor.EnumDescriptor(
  name='MessageType',
  full_name='msgpb.MessageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='None', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Cmd', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CmdResp', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Raft', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='KvReq', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='KvResp', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CopReq', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CopResp', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PdReq', index=8, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PdResp', index=9, number=9,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=505,
  serialized_end=631,
)
_sym_db.RegisterEnumDescriptor(_MESSAGETYPE)

MessageType = enum_type_wrapper.EnumTypeWrapper(_MESSAGETYPE)
Cmd = 1
CmdResp = 2
Raft = 3
KvReq = 4
KvResp = 5
CopReq = 6
CopResp = 7
PdReq = 8
PdResp = 9



_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='msgpb.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg_type', full_name='msgpb.Message.msg_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cmd_req', full_name='msgpb.Message.cmd_req', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cmd_resp', full_name='msgpb.Message.cmd_resp', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='raft', full_name='msgpb.Message.raft', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='kv_req', full_name='msgpb.Message.kv_req', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='kv_resp', full_name='msgpb.Message.kv_resp', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cop_req', full_name='msgpb.Message.cop_req', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cop_resp', full_name='msgpb.Message.cop_resp', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pd_req', full_name='msgpb.Message.pd_req', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pd_resp', full_name='msgpb.Message.pd_resp', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=503,
)

_MESSAGE.fields_by_name['msg_type'].enum_type = _MESSAGETYPE
_MESSAGE.fields_by_name['cmd_req'].message_type = raft__cmdpb__pb2._RAFTCMDREQUEST
_MESSAGE.fields_by_name['cmd_resp'].message_type = raft__cmdpb__pb2._RAFTCMDRESPONSE
_MESSAGE.fields_by_name['raft'].message_type = raft__serverpb__pb2._RAFTMESSAGE
_MESSAGE.fields_by_name['kv_req'].message_type = kvrpcpb__pb2._REQUEST
_MESSAGE.fields_by_name['kv_resp'].message_type = kvrpcpb__pb2._RESPONSE
_MESSAGE.fields_by_name['cop_req'].message_type = coprocessor__pb2._REQUEST
_MESSAGE.fields_by_name['cop_resp'].message_type = coprocessor__pb2._RESPONSE
_MESSAGE.fields_by_name['pd_req'].message_type = pdpb__pb2._REQUEST
_MESSAGE.fields_by_name['pd_resp'].message_type = pdpb__pb2._RESPONSE
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
DESCRIPTOR.enum_types_by_name['MessageType'] = _MESSAGETYPE

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGE,
  __module__ = 'msgpb_pb2'
  # @@protoc_insertion_point(class_scope:msgpb.Message)
  ))
_sym_db.RegisterMessage(Message)


# @@protoc_insertion_point(module_scope)
