# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mvccpb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mvccpb.proto',
  package='mvccpb',
  syntax='proto2',
  serialized_pb=_b('\n\x0cmvccpb.proto\x12\x06mvccpb\"/\n\x08MetaItem\x12\x10\n\x08start_ts\x18\x01 \x01(\x04\x12\x11\n\tcommit_ts\x18\x02 \x01(\x04\"U\n\x08MetaLock\x12\"\n\x04type\x18\x01 \x01(\x0e\x32\x14.mvccpb.MetaLockType\x12\x10\n\x08start_ts\x18\x02 \x01(\x04\x12\x13\n\x0bprimary_key\x18\x03 \x01(\x0c\"U\n\x04Meta\x12\x1e\n\x04lock\x18\x01 \x01(\x0b\x32\x10.mvccpb.MetaLock\x12\x1f\n\x05items\x18\x02 \x03(\x0b\x32\x10.mvccpb.MetaItem\x12\x0c\n\x04next\x18\x03 \x01(\x04*+\n\x0cMetaLockType\x12\x0c\n\x08ReadOnly\x10\x01\x12\r\n\tReadWrite\x10\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_METALOCKTYPE = _descriptor.EnumDescriptor(
  name='MetaLockType',
  full_name='mvccpb.MetaLockType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ReadOnly', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ReadWrite', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=247,
  serialized_end=290,
)
_sym_db.RegisterEnumDescriptor(_METALOCKTYPE)

MetaLockType = enum_type_wrapper.EnumTypeWrapper(_METALOCKTYPE)
ReadOnly = 1
ReadWrite = 2



_METAITEM = _descriptor.Descriptor(
  name='MetaItem',
  full_name='mvccpb.MetaItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_ts', full_name='mvccpb.MetaItem.start_ts', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='commit_ts', full_name='mvccpb.MetaItem.commit_ts', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=71,
)


_METALOCK = _descriptor.Descriptor(
  name='MetaLock',
  full_name='mvccpb.MetaLock',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='mvccpb.MetaLock.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start_ts', full_name='mvccpb.MetaLock.start_ts', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='primary_key', full_name='mvccpb.MetaLock.primary_key', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=158,
)


_META = _descriptor.Descriptor(
  name='Meta',
  full_name='mvccpb.Meta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lock', full_name='mvccpb.Meta.lock', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='items', full_name='mvccpb.Meta.items', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='next', full_name='mvccpb.Meta.next', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=245,
)

_METALOCK.fields_by_name['type'].enum_type = _METALOCKTYPE
_META.fields_by_name['lock'].message_type = _METALOCK
_META.fields_by_name['items'].message_type = _METAITEM
DESCRIPTOR.message_types_by_name['MetaItem'] = _METAITEM
DESCRIPTOR.message_types_by_name['MetaLock'] = _METALOCK
DESCRIPTOR.message_types_by_name['Meta'] = _META
DESCRIPTOR.enum_types_by_name['MetaLockType'] = _METALOCKTYPE

MetaItem = _reflection.GeneratedProtocolMessageType('MetaItem', (_message.Message,), dict(
  DESCRIPTOR = _METAITEM,
  __module__ = 'mvccpb_pb2'
  # @@protoc_insertion_point(class_scope:mvccpb.MetaItem)
  ))
_sym_db.RegisterMessage(MetaItem)

MetaLock = _reflection.GeneratedProtocolMessageType('MetaLock', (_message.Message,), dict(
  DESCRIPTOR = _METALOCK,
  __module__ = 'mvccpb_pb2'
  # @@protoc_insertion_point(class_scope:mvccpb.MetaLock)
  ))
_sym_db.RegisterMessage(MetaLock)

Meta = _reflection.GeneratedProtocolMessageType('Meta', (_message.Message,), dict(
  DESCRIPTOR = _META,
  __module__ = 'mvccpb_pb2'
  # @@protoc_insertion_point(class_scope:mvccpb.Meta)
  ))
_sym_db.RegisterMessage(Meta)


# @@protoc_insertion_point(module_scope)
