# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft_serverpb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import eraftpb_pb2 as eraftpb__pb2
import metapb_pb2 as metapb__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='raft_serverpb.proto',
  package='raft_serverpb',
  syntax='proto2',
  serialized_pb=_b('\n\x13raft_serverpb.proto\x12\rraft_serverpb\x1a\reraftpb.proto\x1a\x0cmetapb.proto\"\xe8\x01\n\x0bRaftMessage\x12\x11\n\tregion_id\x18\x01 \x01(\x04\x12\x1f\n\tfrom_peer\x18\x02 \x01(\x0b\x32\x0c.metapb.Peer\x12\x1d\n\x07to_peer\x18\x03 \x01(\x0b\x32\x0c.metapb.Peer\x12!\n\x07message\x18\x04 \x01(\x0b\x32\x10.eraftpb.Message\x12)\n\x0cregion_epoch\x18\x05 \x01(\x0b\x32\x13.metapb.RegionEpoch\x12\x14\n\x0cis_tombstone\x18\x06 \x01(\x08\x12\x11\n\tstart_key\x18\x07 \x01(\x0c\x12\x0f\n\x07\x65nd_key\x18\x08 \x01(\x0c\"1\n\x12RaftTruncatedState\x12\r\n\x05index\x18\x01 \x01(\x04\x12\x0c\n\x04term\x18\x02 \x01(\x04\"&\n\x08KeyValue\x12\x0b\n\x03key\x18\x01 \x01(\x0c\x12\r\n\x05value\x18\x02 \x01(\x0c\"l\n\x10RaftSnapshotData\x12\x1e\n\x06region\x18\x01 \x01(\x0b\x32\x0e.metapb.Region\x12\x11\n\tfile_size\x18\x02 \x01(\x04\x12%\n\x04\x64\x61ta\x18\x03 \x03(\x0b\x32\x17.raft_serverpb.KeyValue\"2\n\nStoreIdent\x12\x12\n\ncluster_id\x18\x01 \x01(\x04\x12\x10\n\x08store_id\x18\x02 \x01(\x04\"L\n\x0eRaftLocalState\x12&\n\nhard_state\x18\x01 \x01(\x0b\x32\x12.eraftpb.HardState\x12\x12\n\nlast_index\x18\x02 \x01(\x04\"c\n\x0eRaftApplyState\x12\x15\n\rapplied_index\x18\x01 \x01(\x04\x12:\n\x0ftruncated_state\x18\x02 \x01(\x0b\x32!.raft_serverpb.RaftTruncatedState\"[\n\x10RegionLocalState\x12\'\n\x05state\x18\x01 \x01(\x0e\x32\x18.raft_serverpb.PeerState\x12\x1e\n\x06region\x18\x02 \x01(\x0b\x32\x0e.metapb.Region*4\n\tPeerState\x12\n\n\x06Normal\x10\x00\x12\x0c\n\x08\x41pplying\x10\x01\x12\r\n\tTombstone\x10\x02')
  ,
  dependencies=[eraftpb__pb2.DESCRIPTOR,metapb__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_PEERSTATE = _descriptor.EnumDescriptor(
  name='PeerState',
  full_name='raft_serverpb.PeerState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Normal', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Applying', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Tombstone', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=827,
  serialized_end=879,
)
_sym_db.RegisterEnumDescriptor(_PEERSTATE)

PeerState = enum_type_wrapper.EnumTypeWrapper(_PEERSTATE)
Normal = 0
Applying = 1
Tombstone = 2



_RAFTMESSAGE = _descriptor.Descriptor(
  name='RaftMessage',
  full_name='raft_serverpb.RaftMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='region_id', full_name='raft_serverpb.RaftMessage.region_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='from_peer', full_name='raft_serverpb.RaftMessage.from_peer', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='to_peer', full_name='raft_serverpb.RaftMessage.to_peer', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message', full_name='raft_serverpb.RaftMessage.message', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='region_epoch', full_name='raft_serverpb.RaftMessage.region_epoch', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_tombstone', full_name='raft_serverpb.RaftMessage.is_tombstone', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start_key', full_name='raft_serverpb.RaftMessage.start_key', index=6,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end_key', full_name='raft_serverpb.RaftMessage.end_key', index=7,
      number=8, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=300,
)


_RAFTTRUNCATEDSTATE = _descriptor.Descriptor(
  name='RaftTruncatedState',
  full_name='raft_serverpb.RaftTruncatedState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='raft_serverpb.RaftTruncatedState.index', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='term', full_name='raft_serverpb.RaftTruncatedState.term', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=302,
  serialized_end=351,
)


_KEYVALUE = _descriptor.Descriptor(
  name='KeyValue',
  full_name='raft_serverpb.KeyValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='raft_serverpb.KeyValue.key', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='raft_serverpb.KeyValue.value', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=353,
  serialized_end=391,
)


_RAFTSNAPSHOTDATA = _descriptor.Descriptor(
  name='RaftSnapshotData',
  full_name='raft_serverpb.RaftSnapshotData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='region', full_name='raft_serverpb.RaftSnapshotData.region', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='file_size', full_name='raft_serverpb.RaftSnapshotData.file_size', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='raft_serverpb.RaftSnapshotData.data', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=393,
  serialized_end=501,
)


_STOREIDENT = _descriptor.Descriptor(
  name='StoreIdent',
  full_name='raft_serverpb.StoreIdent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cluster_id', full_name='raft_serverpb.StoreIdent.cluster_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='store_id', full_name='raft_serverpb.StoreIdent.store_id', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=503,
  serialized_end=553,
)


_RAFTLOCALSTATE = _descriptor.Descriptor(
  name='RaftLocalState',
  full_name='raft_serverpb.RaftLocalState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hard_state', full_name='raft_serverpb.RaftLocalState.hard_state', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='last_index', full_name='raft_serverpb.RaftLocalState.last_index', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=555,
  serialized_end=631,
)


_RAFTAPPLYSTATE = _descriptor.Descriptor(
  name='RaftApplyState',
  full_name='raft_serverpb.RaftApplyState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='applied_index', full_name='raft_serverpb.RaftApplyState.applied_index', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='truncated_state', full_name='raft_serverpb.RaftApplyState.truncated_state', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=633,
  serialized_end=732,
)


_REGIONLOCALSTATE = _descriptor.Descriptor(
  name='RegionLocalState',
  full_name='raft_serverpb.RegionLocalState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='raft_serverpb.RegionLocalState.state', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='region', full_name='raft_serverpb.RegionLocalState.region', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=734,
  serialized_end=825,
)

_RAFTMESSAGE.fields_by_name['from_peer'].message_type = metapb__pb2._PEER
_RAFTMESSAGE.fields_by_name['to_peer'].message_type = metapb__pb2._PEER
_RAFTMESSAGE.fields_by_name['message'].message_type = eraftpb__pb2._MESSAGE
_RAFTMESSAGE.fields_by_name['region_epoch'].message_type = metapb__pb2._REGIONEPOCH
_RAFTSNAPSHOTDATA.fields_by_name['region'].message_type = metapb__pb2._REGION
_RAFTSNAPSHOTDATA.fields_by_name['data'].message_type = _KEYVALUE
_RAFTLOCALSTATE.fields_by_name['hard_state'].message_type = eraftpb__pb2._HARDSTATE
_RAFTAPPLYSTATE.fields_by_name['truncated_state'].message_type = _RAFTTRUNCATEDSTATE
_REGIONLOCALSTATE.fields_by_name['state'].enum_type = _PEERSTATE
_REGIONLOCALSTATE.fields_by_name['region'].message_type = metapb__pb2._REGION
DESCRIPTOR.message_types_by_name['RaftMessage'] = _RAFTMESSAGE
DESCRIPTOR.message_types_by_name['RaftTruncatedState'] = _RAFTTRUNCATEDSTATE
DESCRIPTOR.message_types_by_name['KeyValue'] = _KEYVALUE
DESCRIPTOR.message_types_by_name['RaftSnapshotData'] = _RAFTSNAPSHOTDATA
DESCRIPTOR.message_types_by_name['StoreIdent'] = _STOREIDENT
DESCRIPTOR.message_types_by_name['RaftLocalState'] = _RAFTLOCALSTATE
DESCRIPTOR.message_types_by_name['RaftApplyState'] = _RAFTAPPLYSTATE
DESCRIPTOR.message_types_by_name['RegionLocalState'] = _REGIONLOCALSTATE
DESCRIPTOR.enum_types_by_name['PeerState'] = _PEERSTATE

RaftMessage = _reflection.GeneratedProtocolMessageType('RaftMessage', (_message.Message,), dict(
  DESCRIPTOR = _RAFTMESSAGE,
  __module__ = 'raft_serverpb_pb2'
  # @@protoc_insertion_point(class_scope:raft_serverpb.RaftMessage)
  ))
_sym_db.RegisterMessage(RaftMessage)

RaftTruncatedState = _reflection.GeneratedProtocolMessageType('RaftTruncatedState', (_message.Message,), dict(
  DESCRIPTOR = _RAFTTRUNCATEDSTATE,
  __module__ = 'raft_serverpb_pb2'
  # @@protoc_insertion_point(class_scope:raft_serverpb.RaftTruncatedState)
  ))
_sym_db.RegisterMessage(RaftTruncatedState)

KeyValue = _reflection.GeneratedProtocolMessageType('KeyValue', (_message.Message,), dict(
  DESCRIPTOR = _KEYVALUE,
  __module__ = 'raft_serverpb_pb2'
  # @@protoc_insertion_point(class_scope:raft_serverpb.KeyValue)
  ))
_sym_db.RegisterMessage(KeyValue)

RaftSnapshotData = _reflection.GeneratedProtocolMessageType('RaftSnapshotData', (_message.Message,), dict(
  DESCRIPTOR = _RAFTSNAPSHOTDATA,
  __module__ = 'raft_serverpb_pb2'
  # @@protoc_insertion_point(class_scope:raft_serverpb.RaftSnapshotData)
  ))
_sym_db.RegisterMessage(RaftSnapshotData)

StoreIdent = _reflection.GeneratedProtocolMessageType('StoreIdent', (_message.Message,), dict(
  DESCRIPTOR = _STOREIDENT,
  __module__ = 'raft_serverpb_pb2'
  # @@protoc_insertion_point(class_scope:raft_serverpb.StoreIdent)
  ))
_sym_db.RegisterMessage(StoreIdent)

RaftLocalState = _reflection.GeneratedProtocolMessageType('RaftLocalState', (_message.Message,), dict(
  DESCRIPTOR = _RAFTLOCALSTATE,
  __module__ = 'raft_serverpb_pb2'
  # @@protoc_insertion_point(class_scope:raft_serverpb.RaftLocalState)
  ))
_sym_db.RegisterMessage(RaftLocalState)

RaftApplyState = _reflection.GeneratedProtocolMessageType('RaftApplyState', (_message.Message,), dict(
  DESCRIPTOR = _RAFTAPPLYSTATE,
  __module__ = 'raft_serverpb_pb2'
  # @@protoc_insertion_point(class_scope:raft_serverpb.RaftApplyState)
  ))
_sym_db.RegisterMessage(RaftApplyState)

RegionLocalState = _reflection.GeneratedProtocolMessageType('RegionLocalState', (_message.Message,), dict(
  DESCRIPTOR = _REGIONLOCALSTATE,
  __module__ = 'raft_serverpb_pb2'
  # @@protoc_insertion_point(class_scope:raft_serverpb.RegionLocalState)
  ))
_sym_db.RegisterMessage(RegionLocalState)


# @@protoc_insertion_point(module_scope)
