# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: volume_cmdpb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='volume_cmdpb.proto',
  package='volume_cmdpb',
  syntax='proto2',
  serialized_pb=_b('\n\x12volume_cmdpb.proto\x12\x0cvolume_cmdpb\"\x1b\n\nAddRequest\x12\r\n\x05\x63ount\x18\x01 \x01(\x04\"!\n\x0b\x41\x64\x64Response\x12\x12\n\nvolume_ids\x18\x01 \x03(\x04\"Y\n\x07Request\x12\'\n\x08\x63md_type\x18\x01 \x01(\x0e\x32\x15.volume_cmdpb.CmdType\x12%\n\x03\x61\x64\x64\x18\x02 \x01(\x0b\x32\x18.volume_cmdpb.AddRequest\"[\n\x08Response\x12\'\n\x08\x63md_type\x18\x01 \x01(\x0e\x32\x15.volume_cmdpb.CmdType\x12&\n\x03\x61\x64\x64\x18\x02 \x01(\x0b\x32\x19.volume_cmdpb.AddResponse*\x1f\n\x07\x43mdType\x12\x0b\n\x07Invalid\x10\x00\x12\x07\n\x03\x41\x64\x64\x10\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_CMDTYPE = _descriptor.EnumDescriptor(
  name='CmdType',
  full_name='volume_cmdpb.CmdType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Invalid', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Add', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=284,
  serialized_end=315,
)
_sym_db.RegisterEnumDescriptor(_CMDTYPE)

CmdType = enum_type_wrapper.EnumTypeWrapper(_CMDTYPE)
Invalid = 0
Add = 1



_ADDREQUEST = _descriptor.Descriptor(
  name='AddRequest',
  full_name='volume_cmdpb.AddRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='count', full_name='volume_cmdpb.AddRequest.count', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=63,
)


_ADDRESPONSE = _descriptor.Descriptor(
  name='AddResponse',
  full_name='volume_cmdpb.AddResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='volume_ids', full_name='volume_cmdpb.AddResponse.volume_ids', index=0,
      number=1, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=98,
)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='volume_cmdpb.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmd_type', full_name='volume_cmdpb.Request.cmd_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='add', full_name='volume_cmdpb.Request.add', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=189,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='volume_cmdpb.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmd_type', full_name='volume_cmdpb.Response.cmd_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='add', full_name='volume_cmdpb.Response.add', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=191,
  serialized_end=282,
)

_REQUEST.fields_by_name['cmd_type'].enum_type = _CMDTYPE
_REQUEST.fields_by_name['add'].message_type = _ADDREQUEST
_RESPONSE.fields_by_name['cmd_type'].enum_type = _CMDTYPE
_RESPONSE.fields_by_name['add'].message_type = _ADDRESPONSE
DESCRIPTOR.message_types_by_name['AddRequest'] = _ADDREQUEST
DESCRIPTOR.message_types_by_name['AddResponse'] = _ADDRESPONSE
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.enum_types_by_name['CmdType'] = _CMDTYPE

AddRequest = _reflection.GeneratedProtocolMessageType('AddRequest', (_message.Message,), dict(
  DESCRIPTOR = _ADDREQUEST,
  __module__ = 'volume_cmdpb_pb2'
  # @@protoc_insertion_point(class_scope:volume_cmdpb.AddRequest)
  ))
_sym_db.RegisterMessage(AddRequest)

AddResponse = _reflection.GeneratedProtocolMessageType('AddResponse', (_message.Message,), dict(
  DESCRIPTOR = _ADDRESPONSE,
  __module__ = 'volume_cmdpb_pb2'
  # @@protoc_insertion_point(class_scope:volume_cmdpb.AddResponse)
  ))
_sym_db.RegisterMessage(AddResponse)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'volume_cmdpb_pb2'
  # @@protoc_insertion_point(class_scope:volume_cmdpb.Request)
  ))
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'volume_cmdpb_pb2'
  # @@protoc_insertion_point(class_scope:volume_cmdpb.Response)
  ))
_sym_db.RegisterMessage(Response)


# @@protoc_insertion_point(module_scope)
