// Code generated by protoc-gen-gogo.
// source: msgpb.proto
// DO NOT EDIT!

/*
	Package msgpb is a generated protocol buffer package.

	It is generated from these files:
		msgpb.proto

	It has these top-level messages:
		Message
*/
package msgpb

import (
	"fmt"
	"io"
	"math"

	proto "github.com/golang/protobuf/proto"

	raft_cmdpb "github.com/pingcap/kvproto/pkg/raft_cmdpb"

	raft_serverpb "github.com/pingcap/kvproto/pkg/raft_serverpb"

	kvrpcpb "github.com/pingcap/kvproto/pkg/kvrpcpb"

	coprocessor "github.com/pingcap/kvproto/pkg/coprocessor"

	pdpb "github.com/pingcap/kvproto/pkg/pdpb"

	volume_cmdpb "github.com/pingcap/kvproto/pkg/volume_cmdpb"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MessageType int32

const (
	MessageType_None       MessageType = 0
	MessageType_Cmd        MessageType = 1
	MessageType_CmdResp    MessageType = 2
	MessageType_Raft       MessageType = 3
	MessageType_KvReq      MessageType = 4
	MessageType_KvResp     MessageType = 5
	MessageType_CopReq     MessageType = 6
	MessageType_CopResp    MessageType = 7
	MessageType_PdReq      MessageType = 8
	MessageType_PdResp     MessageType = 9
	MessageType_VolumeReq  MessageType = 10
	MessageType_VolumeResp MessageType = 11
)

var MessageType_name = map[int32]string{
	0:  "None",
	1:  "Cmd",
	2:  "CmdResp",
	3:  "Raft",
	4:  "KvReq",
	5:  "KvResp",
	6:  "CopReq",
	7:  "CopResp",
	8:  "PdReq",
	9:  "PdResp",
	10: "VolumeReq",
	11: "VolumeResp",
}
var MessageType_value = map[string]int32{
	"None":       0,
	"Cmd":        1,
	"CmdResp":    2,
	"Raft":       3,
	"KvReq":      4,
	"KvResp":     5,
	"CopReq":     6,
	"CopResp":    7,
	"PdReq":      8,
	"PdResp":     9,
	"VolumeReq":  10,
	"VolumeResp": 11,
}

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}
func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}
func (x *MessageType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MessageType_value, data, "MessageType")
	if err != nil {
		return err
	}
	*x = MessageType(value)
	return nil
}
func (MessageType) EnumDescriptor() ([]byte, []int) { return fileDescriptorMsgpb, []int{0} }

// Message holds all messages communicating with TiKV.
type Message struct {
	MsgType          MessageType                 `protobuf:"varint,1,opt,name=msg_type,json=msgType,enum=msgpb.MessageType" json:"msg_type"`
	CmdReq           *raft_cmdpb.RaftCmdRequest  `protobuf:"bytes,2,opt,name=cmd_req,json=cmdReq" json:"cmd_req,omitempty"`
	CmdResp          *raft_cmdpb.RaftCmdResponse `protobuf:"bytes,3,opt,name=cmd_resp,json=cmdResp" json:"cmd_resp,omitempty"`
	Raft             *raft_serverpb.RaftMessage  `protobuf:"bytes,4,opt,name=raft" json:"raft,omitempty"`
	KvReq            *kvrpcpb.Request            `protobuf:"bytes,5,opt,name=kv_req,json=kvReq" json:"kv_req,omitempty"`
	KvResp           *kvrpcpb.Response           `protobuf:"bytes,6,opt,name=kv_resp,json=kvResp" json:"kv_resp,omitempty"`
	CopReq           *coprocessor.Request        `protobuf:"bytes,7,opt,name=cop_req,json=copReq" json:"cop_req,omitempty"`
	CopResp          *coprocessor.Response       `protobuf:"bytes,8,opt,name=cop_resp,json=copResp" json:"cop_resp,omitempty"`
	PdReq            *pdpb.Request               `protobuf:"bytes,9,opt,name=pd_req,json=pdReq" json:"pd_req,omitempty"`
	PdResp           *pdpb.Response              `protobuf:"bytes,10,opt,name=pd_resp,json=pdResp" json:"pd_resp,omitempty"`
	VolumeReq        *volume_cmdpb.Request       `protobuf:"bytes,11,opt,name=volume_req,json=volumeReq" json:"volume_req,omitempty"`
	VolumeResp       *volume_cmdpb.Response      `protobuf:"bytes,12,opt,name=volume_resp,json=volumeResp" json:"volume_resp,omitempty"`
	XXX_unrecognized []byte                      `json:"-"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptorMsgpb, []int{0} }

func (m *Message) GetMsgType() MessageType {
	if m != nil {
		return m.MsgType
	}
	return MessageType_None
}

func (m *Message) GetCmdReq() *raft_cmdpb.RaftCmdRequest {
	if m != nil {
		return m.CmdReq
	}
	return nil
}

func (m *Message) GetCmdResp() *raft_cmdpb.RaftCmdResponse {
	if m != nil {
		return m.CmdResp
	}
	return nil
}

func (m *Message) GetRaft() *raft_serverpb.RaftMessage {
	if m != nil {
		return m.Raft
	}
	return nil
}

func (m *Message) GetKvReq() *kvrpcpb.Request {
	if m != nil {
		return m.KvReq
	}
	return nil
}

func (m *Message) GetKvResp() *kvrpcpb.Response {
	if m != nil {
		return m.KvResp
	}
	return nil
}

func (m *Message) GetCopReq() *coprocessor.Request {
	if m != nil {
		return m.CopReq
	}
	return nil
}

func (m *Message) GetCopResp() *coprocessor.Response {
	if m != nil {
		return m.CopResp
	}
	return nil
}

func (m *Message) GetPdReq() *pdpb.Request {
	if m != nil {
		return m.PdReq
	}
	return nil
}

func (m *Message) GetPdResp() *pdpb.Response {
	if m != nil {
		return m.PdResp
	}
	return nil
}

func (m *Message) GetVolumeReq() *volume_cmdpb.Request {
	if m != nil {
		return m.VolumeReq
	}
	return nil
}

func (m *Message) GetVolumeResp() *volume_cmdpb.Response {
	if m != nil {
		return m.VolumeResp
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "msgpb.Message")
	proto.RegisterEnum("msgpb.MessageType", MessageType_name, MessageType_value)
}
func (m *Message) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Message) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0x8
	i++
	i = encodeVarintMsgpb(dAtA, i, uint64(m.MsgType))
	if m.CmdReq != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintMsgpb(dAtA, i, uint64(m.CmdReq.Size()))
		n1, err := m.CmdReq.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if m.CmdResp != nil {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintMsgpb(dAtA, i, uint64(m.CmdResp.Size()))
		n2, err := m.CmdResp.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n2
	}
	if m.Raft != nil {
		dAtA[i] = 0x22
		i++
		i = encodeVarintMsgpb(dAtA, i, uint64(m.Raft.Size()))
		n3, err := m.Raft.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n3
	}
	if m.KvReq != nil {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintMsgpb(dAtA, i, uint64(m.KvReq.Size()))
		n4, err := m.KvReq.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n4
	}
	if m.KvResp != nil {
		dAtA[i] = 0x32
		i++
		i = encodeVarintMsgpb(dAtA, i, uint64(m.KvResp.Size()))
		n5, err := m.KvResp.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n5
	}
	if m.CopReq != nil {
		dAtA[i] = 0x3a
		i++
		i = encodeVarintMsgpb(dAtA, i, uint64(m.CopReq.Size()))
		n6, err := m.CopReq.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n6
	}
	if m.CopResp != nil {
		dAtA[i] = 0x42
		i++
		i = encodeVarintMsgpb(dAtA, i, uint64(m.CopResp.Size()))
		n7, err := m.CopResp.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n7
	}
	if m.PdReq != nil {
		dAtA[i] = 0x4a
		i++
		i = encodeVarintMsgpb(dAtA, i, uint64(m.PdReq.Size()))
		n8, err := m.PdReq.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n8
	}
	if m.PdResp != nil {
		dAtA[i] = 0x52
		i++
		i = encodeVarintMsgpb(dAtA, i, uint64(m.PdResp.Size()))
		n9, err := m.PdResp.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n9
	}
	if m.VolumeReq != nil {
		dAtA[i] = 0x5a
		i++
		i = encodeVarintMsgpb(dAtA, i, uint64(m.VolumeReq.Size()))
		n10, err := m.VolumeReq.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n10
	}
	if m.VolumeResp != nil {
		dAtA[i] = 0x62
		i++
		i = encodeVarintMsgpb(dAtA, i, uint64(m.VolumeResp.Size()))
		n11, err := m.VolumeResp.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n11
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func encodeFixed64Msgpb(dAtA []byte, offset int, v uint64) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	dAtA[offset+4] = uint8(v >> 32)
	dAtA[offset+5] = uint8(v >> 40)
	dAtA[offset+6] = uint8(v >> 48)
	dAtA[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32Msgpb(dAtA []byte, offset int, v uint32) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintMsgpb(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Message) Size() (n int) {
	var l int
	_ = l
	n += 1 + sovMsgpb(uint64(m.MsgType))
	if m.CmdReq != nil {
		l = m.CmdReq.Size()
		n += 1 + l + sovMsgpb(uint64(l))
	}
	if m.CmdResp != nil {
		l = m.CmdResp.Size()
		n += 1 + l + sovMsgpb(uint64(l))
	}
	if m.Raft != nil {
		l = m.Raft.Size()
		n += 1 + l + sovMsgpb(uint64(l))
	}
	if m.KvReq != nil {
		l = m.KvReq.Size()
		n += 1 + l + sovMsgpb(uint64(l))
	}
	if m.KvResp != nil {
		l = m.KvResp.Size()
		n += 1 + l + sovMsgpb(uint64(l))
	}
	if m.CopReq != nil {
		l = m.CopReq.Size()
		n += 1 + l + sovMsgpb(uint64(l))
	}
	if m.CopResp != nil {
		l = m.CopResp.Size()
		n += 1 + l + sovMsgpb(uint64(l))
	}
	if m.PdReq != nil {
		l = m.PdReq.Size()
		n += 1 + l + sovMsgpb(uint64(l))
	}
	if m.PdResp != nil {
		l = m.PdResp.Size()
		n += 1 + l + sovMsgpb(uint64(l))
	}
	if m.VolumeReq != nil {
		l = m.VolumeReq.Size()
		n += 1 + l + sovMsgpb(uint64(l))
	}
	if m.VolumeResp != nil {
		l = m.VolumeResp.Size()
		n += 1 + l + sovMsgpb(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovMsgpb(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozMsgpb(x uint64) (n int) {
	return sovMsgpb(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Message) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgpb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Message: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Message: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MsgType", wireType)
			}
			m.MsgType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MsgType |= (MessageType(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CmdReq", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgpb
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CmdReq == nil {
				m.CmdReq = &raft_cmdpb.RaftCmdRequest{}
			}
			if err := m.CmdReq.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CmdResp", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgpb
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CmdResp == nil {
				m.CmdResp = &raft_cmdpb.RaftCmdResponse{}
			}
			if err := m.CmdResp.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Raft", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgpb
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Raft == nil {
				m.Raft = &raft_serverpb.RaftMessage{}
			}
			if err := m.Raft.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field KvReq", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgpb
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.KvReq == nil {
				m.KvReq = &kvrpcpb.Request{}
			}
			if err := m.KvReq.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field KvResp", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgpb
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.KvResp == nil {
				m.KvResp = &kvrpcpb.Response{}
			}
			if err := m.KvResp.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CopReq", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgpb
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CopReq == nil {
				m.CopReq = &coprocessor.Request{}
			}
			if err := m.CopReq.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CopResp", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgpb
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CopResp == nil {
				m.CopResp = &coprocessor.Response{}
			}
			if err := m.CopResp.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PdReq", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgpb
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.PdReq == nil {
				m.PdReq = &pdpb.Request{}
			}
			if err := m.PdReq.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PdResp", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgpb
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.PdResp == nil {
				m.PdResp = &pdpb.Response{}
			}
			if err := m.PdResp.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VolumeReq", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgpb
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.VolumeReq == nil {
				m.VolumeReq = &volume_cmdpb.Request{}
			}
			if err := m.VolumeReq.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VolumeResp", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgpb
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.VolumeResp == nil {
				m.VolumeResp = &volume_cmdpb.Response{}
			}
			if err := m.VolumeResp.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMsgpb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMsgpb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMsgpb(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMsgpb
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgpb
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgpb
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthMsgpb
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowMsgpb
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipMsgpb(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthMsgpb = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMsgpb   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("msgpb.proto", fileDescriptorMsgpb) }

var fileDescriptorMsgpb = []byte{
	// 487 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x52, 0xd1, 0x6a, 0xd4, 0x40,
	0x14, 0xdd, 0x74, 0x93, 0x4c, 0x72, 0xe3, 0x2e, 0xd3, 0xb1, 0xca, 0xb2, 0x42, 0x15, 0x11, 0x2a,
	0x05, 0xa3, 0x54, 0xd1, 0xf7, 0xf6, 0xb1, 0x28, 0x25, 0x48, 0x5f, 0x97, 0x9a, 0x8e, 0xfb, 0xb0,
	0x6e, 0x67, 0x9a, 0xd9, 0x06, 0xfc, 0x13, 0x5f, 0xfc, 0x9f, 0xbe, 0xe9, 0x17, 0x88, 0xe8, 0x8f,
	0x78, 0xef, 0x9d, 0x49, 0x9a, 0x16, 0x1f, 0x02, 0x77, 0x66, 0xce, 0x39, 0xf7, 0xdc, 0x73, 0x03,
	0xc5, 0xda, 0x2d, 0xed, 0xa7, 0xd2, 0x36, 0x66, 0x63, 0x54, 0xc2, 0x87, 0xb9, 0x6c, 0xce, 0x3e,
	0x6f, 0x16, 0xf5, 0xfa, 0xbc, 0x7b, 0x98, 0xdf, 0xe7, 0x1b, 0xa7, 0x9b, 0x56, 0x37, 0xfd, 0xe5,
	0x64, 0xd5, 0x36, 0xb6, 0xee, 0x8f, 0xdb, 0xb5, 0xc1, 0xa2, 0xd6, 0xce, 0x99, 0x26, 0x5c, 0x81,
	0xbd, 0x91, 0x50, 0xad, 0xf9, 0x72, 0xb5, 0xd6, 0xb7, 0x64, 0x77, 0x96, 0x66, 0x69, 0xb8, 0x7c,
	0x49, 0x95, 0xbf, 0x7d, 0xfa, 0x23, 0x06, 0xf1, 0x1e, 0x65, 0xce, 0x96, 0x5a, 0xbd, 0x86, 0x0c,
	0x3d, 0x2d, 0x36, 0x5f, 0xad, 0x9e, 0x45, 0x4f, 0xa2, 0xe7, 0xd3, 0x03, 0x55, 0x7a, 0xc7, 0x01,
	0xf1, 0x11, 0x5f, 0x0e, 0xe3, 0xeb, 0x5f, 0x8f, 0x47, 0x95, 0xc0, 0x07, 0x3a, 0x22, 0x49, 0x60,
	0x97, 0x45, 0xa3, 0x2f, 0x67, 0x5b, 0xc8, 0x29, 0x0e, 0xe6, 0xe5, 0x60, 0xa2, 0x0a, 0xcb, 0xa3,
	0xf5, 0x79, 0xa5, 0x2f, 0xaf, 0xb4, 0xdb, 0x54, 0x69, 0xcd, 0xb5, 0x7a, 0x0b, 0x99, 0x27, 0x39,
	0x3b, 0x1b, 0x33, 0xeb, 0xd1, 0x7f, 0x59, 0xce, 0x9a, 0x0b, 0xa7, 0x2b, 0x51, 0xfb, 0x83, 0x2a,
	0x21, 0x26, 0xd8, 0x2c, 0x1e, 0x76, 0xea, 0x93, 0x22, 0x5a, 0x70, 0x5a, 0x31, 0x4e, 0xed, 0x41,
	0xba, 0x6a, 0xd9, 0x5b, 0xc2, 0x0c, 0x59, 0x76, 0x31, 0x76, 0x8e, 0x92, 0x55, 0x4b, 0x86, 0xf6,
	0x41, 0x30, 0x10, 0xfd, 0xa4, 0x8c, 0xdc, 0x1e, 0x20, 0x83, 0x8b, 0x94, 0xa0, 0x68, 0xe2, 0x05,
	0x4e, 0x6c, 0x2c, 0xab, 0x0a, 0xc6, 0xee, 0x94, 0xc3, 0x6d, 0xdc, 0xcc, 0x6a, 0x2c, 0x49, 0xbf,
	0xc2, 0x59, 0x19, 0x8e, 0xda, 0x19, 0xe3, 0x1f, 0xdc, 0xc1, 0xf7, 0x53, 0x12, 0x01, 0x1b, 0x3c,
	0x83, 0xd4, 0xfa, 0x44, 0x73, 0xc6, 0x4f, 0x4a, 0x5e, 0x6d, 0x6f, 0xd9, 0x72, 0x86, 0x7b, 0x20,
	0x6c, 0x88, 0x10, 0x18, 0x36, 0xed, 0x60, 0x9d, 0x5f, 0xeb, 0x43, 0x7b, 0x03, 0x10, 0x7e, 0x07,
	0x92, 0x2c, 0x82, 0x85, 0x5b, 0x7f, 0x48, 0x27, 0x9d, 0xfb, 0x5b, 0x92, 0x7f, 0x07, 0x45, 0xcf,
	0xc2, 0x16, 0xf7, 0x98, 0xf6, 0xf0, 0x2e, 0x2d, 0xb4, 0x82, 0x8e, 0xe7, 0xec, 0xfe, 0xf7, 0x08,
	0x8a, 0xc1, 0xff, 0xa2, 0x32, 0x88, 0x3f, 0x98, 0x0b, 0x2d, 0x47, 0x4a, 0xc0, 0x18, 0xb7, 0x2a,
	0x23, 0x55, 0x80, 0x08, 0xeb, 0x95, 0x5b, 0xf4, 0x4e, 0x8b, 0x93, 0x63, 0x95, 0x43, 0x72, 0x4c,
	0xdb, 0x90, 0xb1, 0x02, 0x48, 0x8f, 0x39, 0x6d, 0x99, 0x50, 0x7d, 0xc4, 0x51, 0xca, 0x94, 0x99,
	0x3e, 0x25, 0x29, 0x08, 0x7f, 0x42, 0x51, 0xc8, 0x8c, 0x30, 0x27, 0x5e, 0x30, 0x57, 0x13, 0xc8,
	0x4f, 0xbb, 0x31, 0x24, 0xa8, 0x29, 0xc0, 0x69, 0xef, 0x4e, 0x16, 0x87, 0xf2, 0xfa, 0xcf, 0x6e,
	0xf4, 0x13, 0xbf, 0xdf, 0xf8, 0x7d, 0xfb, 0xbb, 0x3b, 0xfa, 0x17, 0x00, 0x00, 0xff, 0xff, 0xb8,
	0xf6, 0x04, 0xc4, 0x97, 0x03, 0x00, 0x00,
}
